name: Create Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release Version'
        required: true
        
jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
        
      - name: Setup .NET Core SDK 6.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true
            
      - name: Install dependencies
        run: dotnet restore
      - name: Generate Thumbnails
        run: dotnet run --project ThumbnailGenerator -- ./ ./Portramatic/Resources
      - name: Build App
        run: dotnet build
      - name: Publish
        run: dotnet publish Portramatic -r win-x64 -c Release -p:PublishReadyToRun=true --self-contained -o ./ -p:PublishSingleFile=true -p:DebugType=embedded -p:IncludeAllContentForSelfExtract=true
      - name: Code signing
        uses: DanaBear/code-sign-action@v4
        with:
          # Artifact name
          certificate: "${{ secrets.CODE_CERT }}"
          certificatesha1: "${{ secrets.CODE_CERT_SHA }}"
          password: "${{ secrets.CODE_CERT_PW }}"
          folder: ./
          recursive: false
      - uses: actions/upload-artifact@v2
        with:
          name: Portramatic-${{ github.event.inputs.version }}.exe
          path: Portramatic.exe        