name: Create Release
on:
  workflow_dispatch:

jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-latest
    
    steps:
      - name: Export
        run: mkdir pack && echo "$CODE_CERT" > ./pack/cert && echo "$CODE_CERT_SHA" > ./pack/cert_sha && echo "$CODE_CERT_PW" > ./pack/cert_pw && 
        shell: bash
        env:
          CODE_CERT: ${{ secrets.CODE_CERT}}
          CODE_CERT_SHA: ${{ secrets.CODE_CERT_SHA}}
          CODE_CERT_PW: ${{ secrets.CODE_CERT_PW}}

      - uses: actions/upload-artifact@v2
        with:
          name: pack
          path: ./pack
    